### ISSUE TITLE
gcm_send_message doesn't return anything

### ISSUE THREAD

**Issue by btnz** [jazzband/django-push-notifications#129]
For some reason (possibly something else I've upgraded) push notifications have completely stopped working for me, and while trying to debug why, I notice that gcm.gcm_send_message doesn't return the result, like most of the others do.  I can't see an obvious reason, but is this intentional?

**Comment by jleclanche** [comment]
Most of the others? I don't understand - `apns_send_message` doesn't return anything either.

**Comment by cwliu** [comment]
It worked on version 1.1.0.  When I upgraded to 1.2.0, there is no any response returned by send_message().

**Comment by psychok7** [comment]
@jleclanche is `apns_send_message` supposed to return the json like gcm ?? because its not reuturning for me on the latest commit

**Comment by jleclanche** [comment]
@jamaalscarlett Mind if I assign this to you? I have no idea what's going on.

**Comment by jamaalscarlett** [comment]
@jleclanche sure

**Comment by jamaalscarlett** [comment]
@cwliu are you on the latest version?  Your comment references 1.2.0, but the latest version is 1.4.1?  Have you tried sending directly from the manage shell or django admin?

**Comment by cwliu** [comment]
@jamaalscarlett I don't work on that project anymore, so I have no environment to test it. Sorry.

**Comment by jamaalscarlett** [comment]
@psychok7 So if you roll back to the previous commit does it work again?

**Comment by psychok7** [comment]
@jamaalscarlett which commit exaclty do you want me to test?

**Comment by jamaalscarlett** [comment]
@psychok7 You said the issue started with the latest commit, I assume you mean https://github.com/jleclanche/django-push-notifications/commit/0f90e14dc10ede8d37252fbe7c3032d497fa9d41, could roll back to https://github.com/jleclanche/django-push-notifications/commit/9223deac51a76ce4e7b1f0bdef0777581958b11a

**Comment by psychok7** [comment]
@jamaalscarlett sorry i took so long to answer, i am now using https://github.com/jleclanche/django-push-notifications/commit/fcebfc1a3c66e761f46641977106a1caee7291b0 and `apns_send_message` now returns a string (not json) of the registration i used. if you want me to open a new issue or run more testes let me know (since i am hijacking the gcm one)

**Comment by jamaalscarlett** [comment]
@psychok7 yes, please open a separate issue.  thanks.

**Comment by jamaalscarlett** [comment]
@btnz are you still experiencing this issue?
