### ISSUE TITLE
Can we use different certificates/api keys?

### ISSUE THREAD

**Issue by egamonal** [jazzband/django-push-notifications#130]
in order to send a message to APN and GCM we need to add the settings `APNS_CERTIFICATE`, etc. 
it looks like I can't change the certificate before sending the notifications. is that correct?

my use case is a dashboard where each user has a mobile app that will receive the notifications. these apps are completely independent and can't use the same certificate.

**Comment by jleclanche** [comment]
The ability to use multiple certificates (like django's DATABASES/CACHES dicts) has been brought up before, I can't find it. I'm not opposed to it... I dislike breaking backwards compatibility, but if this proves to be a common request, I'm willing to let it in.

**Comment by jackfengji** [comment]
I also want this feature in my project. I was thinking just add a "key" parameter to the functions. And use that or the default one if it's not provided.

**Comment by evdoks** [comment]
We will be needing this feature as well. We will start working on these extension for our project, so it might be a good place to discuss the design, in case we agree on letting this extension in. Actually, it does not have to break backwards compatibility - we are thinking about storing multiple certificates in a database table, fallbacking to `settings` if the table is empty.

**Comment by jleclanche** [comment]
The certs should most definitely not be in the db.

There should be a setting similar to the current one but presenting a dict that works like django's DATABASES setting.
The current setting should be backwards compatible but raise a deprecation warning.

**Comment by evdoks** [comment]
I don't think it will scale well if certificates are to be managed via a settings file. We are planning to use 10+ different applications, so managing all the certificates will quickly become quite a challenge. You do not want to store certificates in the repo, so it is already tricky enough to manage just one of them. What is your concert with keeping them in the database? [django-ios-notifications](https://github.com/stephenmuss/django-ios-notifications) is doing it this way and it seems to be working pretty well. As I said, backward compatibility should not be an issue.

**Comment by jleclanche** [comment]
Putting settings in the database prevents people from being able to manage their settings by file, simple as that.

If you want it to scale, you can write a settings loader of sorts, seeing as settings are just python file. i don't see the issue. 10 certs, 100 certs, all the same.

**Comment by t-io** [comment]
I see your point for manage settings by file. But unfortunately that's not always possible. For example when you use some PaaS hosting like heroku. I see that it would work with only a few certificates set and extended via environment variables but this scales poor.

**Comment by jleclanche** [comment]
I have a very, very solid -2 on depending on db settings here.

**Comment by niktto** [comment]
Hi, in our use case we also need to store certs and keys in database (clients need to be able to add own mobile apps that they want to push to).

@evdoks - did you already implemented such feature in your fork? It would be awesome if you could share what you did.

If there was no such effort yet taken, I will try my best to implement it myself and then send you, @jleclanche, a pull request - just in case you want to take a look and maybe change your mind about the database case :) (or not, I understand that you might not want to).

By the way, thanks for the awesome package! :+1:

**Comment by jleclanche** [comment]
I'll try to think about a better way of solving this.

**Comment by matthewh** [comment]
@jleclanche This just came up for me as well. I need support for multiple keys for APNS but I do not want the keys in the database.

**Comment by jleclanche** [comment]
Still open to a PR that implements an APNS_CERTIFICATES dict setting.

**Comment by AdamBolfik** [comment]
@jackfengji Adding an extra param(or just passing it thru kwargs) is the same conclusion we came to. This would support backwards compatibility and would allow a clean/easy override for use cases with multiple apps. I'll have the PR up soon.

**Comment by jleclanche** [comment]
8737a4d7beda8f9a1655466a8aa88a44652c7971 adds support for specifying a different certificate to apns_send / send_message().

There's no way to send to a different GCM app, though.

**Comment by jamaalscarlett** [comment]
See: https://github.com/jazzband/django-push-notifications/pull/370
