### ISSUE TITLE
registration_id not unique in GCMDevice

### ISSUE THREAD

**Issue by gulfpearl** [jazzband/django-push-notifications#184]
Not sure why this is the case for APNS and not GCM.

**Comment by jamaalscarlett** [comment]
I've never used APNS but with GCM, google supplies the registration_id.  The device_id and registration_id could be a primary key, but even that is not necessary because the GCM server will return a mismatch error if the registration_id and device_id don't match.

**Comment by gulfpearl** [comment]
Not sure what a mismatch error has to do with this, when registering the device with django, right now if you use the rest api, you can register the same device_id and registration_id pair multiple times, at least through the tastypie interface, haven't looked at the DRF yet. I don't think this is the intended behaviour. 

Also, the unique constraint should be independent to the device_id as it isn't really required for using GCM.

**Comment by jamaalscarlett** [comment]
In order for to make the registration_id unique, you would have to be sure that any un-used device was deleted and not just set inactive.  You don't know what registration_id google is going to send you so making the registration_id unique could result in the following.

1. device a is registered with registration_id foobar.
2. device a uninstalls the android app.
3. the django app attempts to send a push notification to device a
4. the gcm server responds with device not registered and device a is set to inactive in db
5. device b is registered and google sends a registration_id of foobar again(this may be unlikely but you have no idea what id google will send)
6. a unique constraint error would be thrown.

This implementation should be handled in your app.
