### ISSUE TITLE
Strive for same-model behaviour between GCM and APNS

### ISSUE THREAD

**Issue by Vektrat** [jazzband/django-push-notifications#197]
When creating devices, APNS defaults 'device_id' to None, whilst GCM defaults it to "" (empty string), it may be nitpicking but I believe a similar behaviour would be benefitial.

Thank you for your time!

**Comment by jleclanche** [comment]
I don't disagree. Feel free to PR a change as long as it's tested and doesn't break backwards compatibility.

**Comment by Vektrat** [comment]
Ok will do :)

Additionally, is there any reason why duplicate registration_id's are allowed on GCMDevices?

**Comment by jleclanche** [comment]
Making a TextField unique messes with some database engines.

**Comment by matthewh** [comment]
Allowing unique duplicate registration_ids on GCM seems like a bug. Any chance it can just be a CharField with a max of 254 (or similar)?

**Comment by jleclanche** [comment]
registration ids have no predefined length in GCM. I remember reading something about 2000 character reg IDs on SO.

**Comment by matthewh** [comment]
On which database engines does a Unique text field cause issues?

**Comment by jleclanche** [comment]
mysql.

**Comment by lukeburden** [comment]
This seems like a decision to either have correct functioning of the library for most backends, or full DB portability with some quirks for all. Is that policy a conscious decision? (GCMDeviceAuthorizedViewSet allows creation of dupe registration tokens, in turn breaking it's own /device/gcm/<registration_id> URL scheme)

PG, MySQL and SQLite all support massive varchars. Oracle support up to 4000 bytes. I'm wondering whether it wouldn't make more sense to use a CharField(max_length=4096(4000 for Oracle), db_index=True) for GCMDevice.registration_id. Within the library logic you would then enforce uniqueness through checking for pre-existence atomically on create.

Installations using Oracle would be vulnerable in the case where tokens exceed 4000 bytes, but it seems highly improbable that tokens that big will be granted.

**Comment by matthewh** [comment]
The device_id for APNSDevice is Django's UUIDField and it returns None which only leaves patching this project's implementation of [HexIntegerField to return None instead of an empty string](https://github.com/jleclanche/django-push-notifications/blob/master/push_notifications/fields.py#L70). If this is acceptable I will submit a PR.
