### ISSUE TITLE
Web Push API support

### ISSUE THREAD

**Issue by jleclanche** [jazzband/django-push-notifications#276]
https://www.w3.org/TR/push-api/

I'm looking for someone who's willing to contribute a web push API to django-push-notifications. Let me know if you intend to work on this.

**Comment by jamaalscarlett** [comment]
I've started looking at the spec now that Firefox has included it in their browser.  I'm willing to take a shot at it if no one else is interested.

**Comment by jleclanche** [comment]
:+1:

**Comment by jamaalscarlett** [comment]
Some other resources:
https://hacks.mozilla.org/2015/10/keep-pushing-it-with-the-w3c-push-api/
https://github.com/chrisdavidmills/push-api-demo

**Comment by safwanrahman** [comment]
Implemented with [Django Webpush](https://github.com/safwanrahman/django-webpush)

**Comment by jamaalscarlett** [comment]
Looks good.

**Comment by mnoorenberghe** [comment]
Was this fixed by #434?

**Comment by goinnn** [comment]
Yes @jleclanche, @jamaalscarlett it is done!

**Comment by sevdog** [comment]
As of now also Microsoft Edge supports push API, see [caiuse](https://caniuse.com/#search=push%20notifications).

It should be added in `BROWSER_TYPES`.

Also actual example code regex identifies Edge as Chrome.
```
/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
```

**Comment by jamaalscarlett** [comment]
Closing this as webpush is currently supported.
