### ISSUE TITLE
Send Message Return Only Message Id

### ISSUE THREAD

**Issue by rahulpuroht** [jazzband/django-push-notifications#297]
Hey When i try to Send Push Notification Its only return 
GCMDevice.objects.get(pk=6).send_message("hello")
'id=0:1463239201813309%c18df41ef9fd7ecd'
What this id means??
How do i know its Success or Fail
&& 
In APNSDevice Where to put passphrase for pem file ..??

**Comment by jamaalscarlett** [comment]
regarding the first question:'id=0:1463239201813309%c18df41ef9fd7ecd' indicates a successful message.  see: https://developers.google.com/cloud-messaging/http
