### ISSUE TITLE
Multiple certificate for push notification (apns)

### ISSUE THREAD

**Issue by khantthulinn** [jazzband/django-push-notifications#330]
Actually,  this might not be issue but I don't know how to contact developers. 

I am using this django-push-notifications and it is working well for my push notification. Problem now is that I have an app which have both pro and lite version. As a result, I have 2 certificate to send push notification. 

May I know whether multiple push certificate is supported? If so, how shall I do?

**Comment by jleclanche** [comment]
If you're using the low level functions, you can pass the `certfile` argument to them:

https://github.com/jleclanche/django-push-notifications/commit/8737a4d7beda8f9a1655466a8aa88a44652c7971

**Comment by khantthulinn** [comment]
Thanks. I will check out. But I am not using low level function though.

**Comment by dulaccc** [comment]
Btw, it works also if you are using higher methods like `.send_message`.

**Comment by matthewh** [comment]
@jleclanche I believe #366 solves this issue. @khantthulinn would define two application configs, pro and lite, with a unique cert for each. What do you think?

**Comment by khantthulinn** [comment]
I would love to try. Is it available already ?

**Comment by matthewh** [comment]
@khantthulinn It is available if you use the master branch.

The setup instructions are on the wiki for [Muliple Application Support](https://github.com/jleclanche/django-push-notifications/wiki/Multiple-Application-Support).

## PUSH_NOTIFICATIONS_SETTINGS

Sample settings with a pro and lite applications defined.

```
PUSH_NOTIFICATIONS_SETTINGS = {
  # Load and process all PUSH_NOTIFICATIONS_SETTINGS using the AppConfig manager.
  "CONFIG": "push_notifications.conf.AppConfig",

  # collection of all defined applications
  "APPLICATIONS": {
    "pro": {
      # PLATFORM (required) determines what additional settings are required.
      "PLATFORM": "APNS",

      # required APNS setting
      "CERTIFICATE": "/path/to/your/certificate.pem",
    },
    "lite": {
      # PLATFORM (required) determines what additional settings are required.
      "PLATFORM": "APNS",

      # required APNS setting
      "CERTIFICATE": "/path/to/your/certificate.pem",
    }
  }
}
```

**Comment by khantthulinn** [comment]
Thanks. I will let you know again when I manage to set up dev server.

**Comment by matthewh** [comment]
I'm closing this issue. The project has had multiple application support in release builds for a while.
