### ISSUE TITLE
APNs Auth Key support

### ISSUE THREAD

**Issue by anas-aldrees** [jazzband/django-push-notifications#351]
Hi everyone, I think it is good idea to add APNs Auth Key support beside APNs certificate

**Comment by jleclanche** [comment]
Do you have a link to some documentation? I'll take a PR for it.

**Comment by anas-aldrees** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

**Comment by JesseCrocker** [comment]
Is anyone currently working on this? If not i'll probably give it a go

**Comment by jleclanche** [comment]
Go ahead.

**Comment by JesseCrocker** [comment]
I spent some time working on this, then gave up and decided to just use https://github.com/genesluder/python-apns instead.

**Comment by jleclanche** [comment]
FWIW I'd love it if the current APNS logic would be ported to use python-apns as a lib.

**Comment by shigmas** [comment]
It'd be great to support Auth Key tokens through another package, but I think pyapns only supports certificates. python-apns depends on hyper, which I would like to look at more closely before adding that requirement to this.

I'm back to using APNS (and GCM eventually), so I'll do some research.

**Comment by kit-cat** [comment]
It seems like https://github.com/Pr0Ger/PyAPNs2, which we're currently using for the APNS part, only supports certificates - maybe they would take a PR to support auth keys as well

**Comment by shigmas** [comment]
Oh! I didn't realize that you had already done the work! Thanks! I'm just getting back into this after a long absence. I'll take a look at that and see how much work that will take.

**Comment by kit-cat** [comment]
No problem ! :)

**Comment by eskhool** [comment]
PyAPNS2 has support for token authentication now so it is a trivialish exercise to add support now (by taking another conf setting for it)....is anybody looking into this?

**Comment by eskhool** [comment]
@jleclanche, are you still open to a PR for this?

**Comment by shigmas** [comment]
I added the support on PyAPNS2. After that was accepted, I submitted  PR for the JWT auth. It sat for several months to get accepted, so I just used my own fork. So, it's there, just with merge conflicts. Feel free to take that.

**Comment by jleclanche** [comment]
The PR (#426) is good to merge once the last requested changes are done IIRC.
