### ISSUE TITLE
APNS_USE_SANDBOX setting is not respected 

### ISSUE THREAD

**Issue by cketant** [jazzband/django-push-notifications#396]
Documentation states
- `APNS_USE_SANDBOX`: Use 'api.development.push.apple.com', instead of default host 'api.push.apple.com'.

Setting `APNS_USE_SANDBOX` in the `PUSH_NOTIFICATIONS_SETTINGS` has no affect because it is determined by the DJANGO DEBUG environment variable. See `django-push-notifications/push_notifications/settings.py` line 25-28. `APNS_USE_SANDBOX` is overridden by the DJANGO DEBUG environment variable. 

Solution here would be to either update documentation to match the above or source change to respect `APNS_USE_SANDBOX`

**Comment by chrisballinger** [comment]
Shouldn't `setdefault` only set a value if one isn't present? I am having trouble getting the sandbox setting to work myself after updating to 1.5.0.

**Comment by cketant** [comment]
@chrisballinger I overlooked that, that is true. Not exactly sure then why it is being ignored. My workaround was simply to make sure `DEBUG=True`.

**Comment by chrisballinger** [comment]
I did some more debugging and am not having trouble with the setting itself, but can't seem to get sandboxed notifications anymore. Perhaps my latest debug provisioning profile is wrong, cause I know the cert is valid and worked previously.

**Comment by jleclanche** [comment]
@kit-cat any idea? was it reimplemented with pyapns2?

**Comment by kit-cat** [comment]
Sorry for not answering earlier, didn't see the notification - I'll have a look at this tomorrow!

**Comment by chrisballinger** [comment]
So I've determined that my issue wasn't from the sandbox setting, but from `MissingTopic` being returned in the `result` array. Perhaps the topic isn't being auto-guessed from the cert like it says in the docs?

```python
def apns_send_bulk_message(
	registration_ids, alert, application_id=None, certfile=None, **kwargs
):
	"""
	Sends an APNS notification to one or more registration_ids.
	The registration_ids argument needs to be a list.

	Note that if set alert should always be a string. If it is not set,
	it won"t be included in the notification. You will need to pass None
	to this for silent notifications.
	"""

	results = _apns_send(
		registration_ids, alert, batch=True, application_id=application_id,
		certfile=certfile, **kwargs
	)
	inactive_tokens = [token for token, result in results.items() if result == "Unregistered"]
	models.APNSDevice.objects.filter(registration_id__in=inactive_tokens).update(active=False)
	return results
```

**Comment by chrisballinger** [comment]
Would it make sense to collect other "result" values and make them available further up the stack to handle errors like this in application code?

**Comment by kit-cat** [comment]
There is indeed a mistake in the docs - `topic` is mandatory in PyAPNS2 as they always add the `apns-topic` header, it isn't guessed from the cert file (see https://github.com/Pr0Ger/PyAPNs2/issues/29). I've made a pull request to edit the docs to reflect this.
I guess you've opened https://github.com/jleclanche/django-push-notifications/issues/398 for your second question?

**Comment by andreyshipilov** [comment]
Can confirm. Still a bug. For multiple apps config had to set `'USE_SANDBOX': True` per each one. This one works.

**Comment by string-areeb** [comment]
Working fine for me
