### ISSUE TITLE
Removing the unique device constraint

### ISSUE THREAD

**Issue by nikilster** [jazzband/django-push-notifications#41]
I want to remove the unique device id constraint - there are a lot of situations where we want to allow multiple users to register on the same device.  What's the best way to do this?  Also does removing the constraint on the db level (/ model level? ) cause any parts of the code to change in its function?

**Comment by adamsc64** [comment]
@guitarmanvt:  Be careful, notifications can go to the app regardless of who is logged in. As Google recommends:
`The app running on the device should check to ensure that messages it receives match the logged in user.`
From: https://developer.android.com/google/gcm/adv.html#unreg-why

They recommend that you include user identification in the data sent in the message, and only show messages if the correct user is logged in.

**Comment by jleclanche** [comment]
That seems incredibly foolish as the user still receives the data. A clever user will be able to read the data regardless.

I'm rejecting this based on the discussion here. If you absolutely need non-unique, you can safely modify your database to drop the constraint, nothing bad should happen in the app side.

**Comment by eLod** [comment]
@jleclanche would you consider relaxing the uniqueness constraint to be scoped to (`unique_with`) user id, at least for iOS apps (APNSDevice)? As far as i know it's a common use-case to let users sign in with multiple accounts in the same app (on the same device) and receive notifications for all of them. When sending it can take the unique list of registration ids (or even send duplicated messages), but it's controllable. My problem is i'm not sure how i'm supposed to just 'safely modify your database to drop the constraint', or rather how that supposed to work wrt. the drf api views, those would still try to enforce the original model field's uniqueness, or am i missing something? Should i be create a custom model and custom api views?

**Comment by jleclanche** [comment]
I will accept a pull request that makes it configurable but defaults to the current behaviour.
