### ISSUE TITLE
Support for `apns-collapsed-id`

### ISSUE THREAD

**Issue by ezheidtmann** [jazzband/django-push-notifications#429]
It appears that this package does not support the APNS feature `apns-collapse-id`. The apns2 library includes support as a kwarg to `send_notification` or `send_notification_batch` but that kwarg cannot be set via this package's `_apns_send()`.

I don't have a fix available, just documenting that this feature appears to be missing. Thanks.

**Comment by ezheidtmann** [comment]
Whoops, I was looking at the wrong client library. Updated issue description.

**Comment by roshanr95** [comment]
Any updates on this?

**Comment by ezheidtmann** [comment]
@roshanr95 The PR is working for me in production. If you can run the tests & review my work, that could help get it included in a future release. Thanks.

**Comment by alemangui** [comment]
Will this fix be included in an upcoming release? Would be very useful

**Comment by matthewh** [comment]
This is fixed on master and will be present in the next release.
