### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by elcolie** [jazzband/django-push-notifications#459]
>> You can learn more about APNS certificates here.

Apple doc is dead https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

**Comment by AdamDonna** [comment]
Hey @elcolie would this [link's](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/index.html#//apple_ref/doc/uid/TP40008194) suggested be replacement, [this](https://developer.apple.com/documentation/usernotifications) be sufficient. Or are you suggesting removing the link?

**Comment by elcolie** [comment]
In my opinion. Removing will cut off the future document problem.

**Comment by matthewh** [comment]
The [link](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html) was [updated](https://github.com/jazzband/django-push-notifications/commit/c4a0d710711fa27bfb6533c0bf3468cb67a62679#diff-88b99bb28683bd5b7e3a204826ead112) by @AustinFuller.
