### ISSUE TITLE
best way to impliment django notification system in my app

### ISSUE THREAD

**Issue by rahul6612** [jazzband/django-push-notifications#460]
i created a app where peoples can like/unlike posts they can follow/unfollow  to each other and my question is:
1. when **user A** like/unlike **user B** posts, **user B** get the notification (**user A** liked/unliked your post)
2. when **user A** follow **user B**,  **user B** get the notification(**user A** follow you)
3. i have no idea about it so which is the best way to implement it.
4. notification system shoult be fast and roboust means its should show without reloading the page

any idea

**Comment by jamaalscarlett** [comment]
This is a design question.  I'm not sure where it would go, but I don't think it belongs in the issues list.
