### ISSUE TITLE
[Android] FCM Messages do not wake up screen/vibrate/play sound like firebase console

### ISSUE THREAD

**Issue by SrdjanCosicPrica** [jazzband/django-push-notifications#464]
Hi! 

First off, thanks for this great library and support!

Second. When I send a message to FCM like so
```
s.gcmdevice_set.all().send_message('Hej', extra={'extra': 'this is extra data'})
```
,where `s` is a a user, the phone does not vibrate or wake up my screen when in locked mode. The message is there when i wake it up manually but nothing happens when it is actually received. The reason I think it is your library that is maybe missing something is because when I send it from the firebase console it works as expected and wakes my screen and vibrates.

Like I said, the notification is there, it just does not wake up the phone.

**Comment by SrdjanCosicPrica** [comment]
I would like to but I am not quite sure how to do that. To get a precise comparison as possible. Do you know how? @jamaalscarlett

**Comment by jamaalscarlett** [comment]
@SrdjanCosicPrica You need to add some debug logging to your Android app.

**Comment by SrdjanCosicPrica** [comment]
@jamaalscarlett I will try to do a bit more but the thing is that my onMessageReceived is not even trigger when the app is in background/killed. Not even from the firebase console so I'm not quite sure how that is possible

**Comment by SrdjanCosicPrica** [comment]
@jamaalscarlett Yeah you were right in suspecting that I was missing some keyword arguments. I was missing the `sound` kwarg, which defaults to 'disabled'. Setting it to 'enabled' woke it up. Thank you very much.

**Comment by jamaalscarlett** [comment]
@SrdjanCosicPrica My pleasure.
