### ISSUE TITLE
APNS: BadDeviceToken

### ISSUE THREAD

**Issue by dobrovolsky** [jazzband/django-push-notifications#467]
Hi there.
I got an issue with sending notification to ios.
I have production.pem file
but when i'm trying to send notification get error `BadDeviceToken`
When i use service like [pushtry](http://pushtry.com/) i get notification.
Maybe somebody knows what is going on?

**Comment by klepov** [comment]
Hi. how fix it?

**Comment by afzoun** [comment]
https://github.com/jazzband/django-push-notifications/issues/465
