### ISSUE TITLE
Add documentation for multiple application support

### ISSUE THREAD

**Issue by koedal** [jazzband/django-push-notifications#475]
This commit added the ability to have multiple applications configured but didn't include any documentation on how to configure the settings. After reading test cases and trial and error I think I figured it out. Please add docs for the settings for multiple application support.

https://github.com/jazzband/django-push-notifications/commit/a6bc50960006e49950ee9be8bc87fed030929132

**Comment by matthewh** [comment]
Please let me know what needs clarification.

https://github.com/jazzband/django-push-notifications/wiki/Multiple-Application-Support

**Comment by koedal** [comment]
An example of sample settings would be ideal. I think this is correct but it took me way longer to piece together than it should have.

The docs don't mention the CONFIG settings, for example.

```
PUSH_NOTIFICATIONS_SETTINGS = {
    "CONFIG": "push_notifications.conf.AppConfig",
    "UPDATE_ON_DUPLICATE_REG_ID": True,
    "APPLICATIONS": {
        "some_apns_id": {
            "PLATFORM": "APNS",
            "CERTIFICATE": "/var/www/application/aps.pem",
            "TOPIC": "some topic",
            "USE_SANDBOX": False
        },
        "some_fcm_id": {
            "PLATFORM": "FCM",
            "API_KEY": "...",
        }
    }
}
```

**Comment by koedal** [comment]
You could also improve the wiki landing page to have a table of contents. I had looked at the wiki but didn't even see the page reference about it.

<img width="1021" alt="screen shot 2018-10-04 at 8 02 05 pm" src="https://user-images.githubusercontent.com/1350867/46510766-8ae38a80-c810-11e8-978e-ebc8b4238fdd.png">

**Comment by matthewh** [comment]
@koedal I've added links for the Multiple Application Support page into README and wiki.
