### ISSUE TITLE
How to allow one django project alow to different application notification settings. 

### ISSUE THREAD

**Issue by chetanghadawaje** [jazzband/django-push-notifications#479]
PUSH_NOTIFICATIONS_SETTINGS = {
'FCM_API_KEY': '[key]',
"FCM_ERROR_TIMEOUT": 1800,
'APNS_CERTIFICATE': os.path.join(BASE_DIR, "[.pem]"),
"APNS_USE_SANDBOX": "api.development.push.apple.com",
"UPDATE_ON_DUPLICATE_REG_ID": True, 
"APNS_USE_SANDBOX":True
}

above setting declared two times with two different app

**Comment by matthewh** [comment]
Please read the wiki entry for [Multiple Application Support](https://github.com/jazzband/django-push-notifications/wiki/Multiple-Application-Support).
