### ISSUE TITLE
FCM data message logic is buggy/wrong ...unable to send pure data message

### ISSUE THREAD

**Issue by eskhool** [jazzband/django-push-notifications#483]
Using the following command to send data messages to the app does not seem to work as per documentation (they appear to be going as notifications+data payload always)

The logic in the code always assumes that if the list of FCM_NOTIFICATION_PAYLOAD_KEYS is present in the data dictionary they should always be sent as notification payload. This forces the payload to become notification+data and one is unable to send a pure data payload.

**Comment by matthewh** [comment]
@eskhool I encountered this as well when we switched from GCM to FCM. There is a flag hidden deep in the code to send a pure data message just like GCM does. I'm am unsure why this flag wasn't reversed as I would have assumed that FCM and GCM should have behaved the same at the time and the flag would be needed to trigger the alternate behavior. 

```
GCMDevice.objects.all().send_message(use_fcm_notifications=False, **gcm_data)
```

**Comment by matthewh** [comment]
Closing, the question has been answered.
