### ISSUE TITLE
Where BareDevice & DeviceManager

### ISSUE THREAD

**Issue by MySecondLanguage** [jazzband/django-push-notifications#495]
Long Day ago, I notice, there was two class in django-push-notification, it was BareDevice and DeviceManager, but now i notice, these class is not exist.

Can you please tell me, in which version, BareDevice and DeviceManager class exist?

Thanks

**Comment by matthewh** [comment]
Checkout this [fork](https://github.com/AndreasBackx/django-push-notifications).
