### ISSUE TITLE
Web Push Notification Document required

### ISSUE THREAD

**Issue by elcolie** [jazzband/django-push-notifications#498]
I am trying to use `Web Push Notification`. The Django side I have followed all the way through. However, to test the system I have to run with frontend either.

**Problem:**<br>
I don't understand how to follow the given `Utils functions`. They are many questions raise in my header for example. Where I can put server url to it?
I have seen it is opened issue but @goinnn said it is done #276 

**Question:**<br>
Where I can find the example of `Web Push Notification` according to `django-push-notification`? I am willing to contribute the document part in my blog in order to support the community

**Comment by elcolie** [comment]
Article will come after this shortly. Thanks to [mosetail](https://stackoverflow.com/questions/56217113/how-to-implement-web-client-with-django-push-notifications/56221615#56221615) for the answer

**Comment by elcolie** [comment]
https://medium.com/@sarit.r/unified-3-type-of-push-notification-with-django-push-notifications-feeb5f42df7e

**Comment by elcolie** [comment]
![image](https://user-images.githubusercontent.com/18206728/59207617-95d99080-8bd1-11e9-96e5-5b648d44ba97.png)
How to change `TITLE DEFAULT, and localhost:63342`?

**Comment by nlittlejohns** [comment]
@elcolie late reply, but better late than never eh?

I've just been figuring this out myself, I've posted a solution here: https://github.com/jazzband/django-push-notifications/issues/557#issuecomment-584992502

**Comment by elcolie** [comment]
Some one need to revise document!

**Comment by nlittlejohns** [comment]
I can update the docs with some tips once I've got everything a bit more figure out.

**Comment by nlittlejohns** [comment]
@elcolie I've submitted a PR with expanded documentation based on my experience over the last 24 hours of using Web Push. #558
