### ISSUE TITLE
unpinned dependencies (apns2)

### ISSUE THREAD

**Issue by RobertoMaurizzi** [jazzband/django-push-notifications#513]
apns2 released a 0.6.0 version that uses type hinting and as such won't work on Python versions older than 3.5.0

**Comment by odinuge** [comment]
Hi,

Thanks for noticing the issue. A new version,`v1.6.1`, is now released to pypi with `apns2<0.6.0` pinned.

Full changelog can be found here: https://github.com/jazzband/django-push-notifications/blob/master/CHANGELOG.md
