### ISSUE TITLE
apns2 version

### ISSUE THREAD

**Issue by franciscouzo** [jazzband/django-push-notifications#520]
Instead of requiring `apns2>=0.3.0,<0.6.0` for all python versions, it's possible to tell setuptools that a version is required for only a specific python version:

```
apns2>=0.3.0,<0.6.0;python_version<"3.5"
apns2>=0.3.0,<0.7.0;python_version>="3.5"
```

**Comment by odinuge** [comment]
Fixed in #524. Will be a part of the next release
