### ISSUE TITLE
I got exception KeyError when send_message()

### ISSUE THREAD

**Issue by teripak** [jazzband/django-push-notifications#526]
Hi, 
I have below error when I send a web push message by using send_message("test message")
```python
        from push_notifications.models import WebPushDevice

        try:

            devices = WebPushDevice.objects.filter(Q(user=request.user))

            for d in devices:

                d.send_message("test message")

        except Exception as e:

            print('%s => %s (%s)' % ('Exception: device_reg', e, type(e)))

```

### Exception: device_reg => 'Chrome' (<class 'KeyError'>)

The environments are
Django==2.2.4
django-push-notifications==1.6.1

and the WebPush device info is as below.

![send_message_error](https://user-images.githubusercontent.com/3594627/64086164-98cbc380-cd71-11e9-83e2-775b4f98814c.png)

Thank you in advance

**Comment by azmeuk** [comment]
Fixed by #674
