### ISSUE TITLE
IntegrityError: Key (user_id) is not present in table "auth_user"

### ISSUE THREAD

**Issue by HeroSony** [jazzband/django-push-notifications#529]
After changing USER_MODEL setting, and try to attempt insert new gcmdevice record it getting this error.

```python
IntegrityError at /admin/push_notifications/gcmdevice/add/
insert or update on table "push_notifications_gcmdevice" violates foreign key constraint "push_notifications_gcmdevice_user_id_f3752f1b_fk_auth_user_id"
DETAIL:  Key (user_id)=(11) is not present in table "auth_user".
```

**Comment by matthewh** [comment]
@HeroSony [Changing **USER_MODEL** after starting a project](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project) is generally frowned upon.
