### ISSUE TITLE
Use new FCM APIs

### ISSUE THREAD

**Issue by sevdog** [jazzband/django-push-notifications#546]
As of now FCM notifications are sent to `https://fcm.googleapis.com/fcm/send` which is a [legacy API](https://firebase.google.com/docs/cloud-messaging/http-server-ref).

Messages should be sent to [current API endpoint](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send):
```
https://fcm.googleapis.com/v1/{parent=projects/*}/messages:send
```

**Comment by shamilbuzz** [comment]
You can change the API Endpoint for FCM by setting an attribute in push notification config as follows,

```
PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": "********",
    "FCM_POST_URL": "https://fcm.googleapis.com/v1/projects/{project_id}/messages:send",
     .......
     .......
}
```

**Comment by shamilbuzz** [comment]
Now what I can suggest is that **the default FCM POST URL should be changed to new format by adding a mandatory parameter "PROJECT_ID" in FCM Config**

**Comment by shamilbuzz** [comment]
Sorry for my previous replies. I had just started looking into the documents today.
Just now I have found that, for new FCM updates, another way is already implemented in this library. (Thanks to the contributors)

Follow this document here: (Was mentioned as hot-linked in repository's main readme)
https://github.com/jazzband/django-push-notifications/wiki/Multiple-Application-Support

**Comment by sevdog** [comment]
What concern me is that since APIs are different they accept different parameter format.

Looking into Firebase docs seems that [API v1](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send#request-body
) has a different param signature from [legacy](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) one.

There is an official [guide](https://firebase.google.com/docs/cloud-messaging/migrate-v1) which explains why _just changing URL is not enough_.

**Comment by williams9438** [comment]
> What concern me is that since APIs are different they accept different parameter format.
> 
> Looking into Firebase docs seems that [API v1](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send#request-body) has a different param signature from [legacy](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) one.
> 
> There is an official [guide](https://firebase.google.com/docs/cloud-messaging/migrate-v1) which explains why _just changing URL is not enough_.

Where you able to solve this??

**Comment by sevdog** [comment]
> Where you able to solve this??

ATM I do not have time to work on a PR about this issue.

Since Google is still maintaining legacy API (to keep alive many legacy app) this is not an high-priority.

When I have some free time I could try to address this.

**Comment by sevdog** [comment]
This could be accomplished by using official [`firebase-admin`](https://pypi.org/project/firebase-admin/) or by using the [example code](https://github.com/firebase/quickstart-python/blob/master/messaging/messaging.py) provided by firebase guide.

**Comment by shamilbuzz** [comment]
> What concern me is that since APIs are different they accept different parameter format.
> 
> Looking into Firebase docs seems that [API v1](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send#request-body) has a different param signature from [legacy](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json) one.
> 
> There is an official [guide](https://firebase.google.com/docs/cloud-messaging/migrate-v1) which explains why _just changing URL is not enough_.

First of all, sorry to be not responsive here as it's my secondary github account. Seems like I went for a winter sleep :P 

Thanks, @sevdog for pointing the issue with my short reply. Yes, just changing URL is not enough here and actually its not the true solution in any system anywhere. 
So AT THAT TIME, how I solved was by overriding few core methods for myself following the official that you had also mentioned in your reply. So I actually had to customize the library on a short notice to meet my deadline. But unfortunately, that was not something to be shared with public or send a PR as well :D 

@sevdog , thanks again for your latest suggestion, I will go through this new library as I predict that I will have to work on push notifications soon and quite on a large scale TBH. :D

**Comment by sevdog** [comment]
The legacy API are [deprecated from yesterday and will be removed on June 20th 2024](https://firebase.google.com/docs/cloud-messaging/http-server-ref?hl=en)

**Comment by sevdog** [comment]
Looking aroud there is this package which implements only FCM: https://github.com/xtrinch/fcm-django/

It can be taken as an example.
