### ISSUE TITLE
Support for django3

### ISSUE THREAD

**Issue by mousetail** [jazzband/django-push-notifications#550]
Currently, this module uses legacy APIs like `six` and `python2_unicode_compatible`. These have been deprecated for a long time and now have been removed removed from django3.0 onward. `python2_unicode_compatible` has no effect in python3, and can be safely removed. `six.string_types` can be safely replaced by `str`.

**Comment by shree-ranga** [comment]
I had to replace all the "django.utils.six" to just "import six"

**Comment by elcolie** [comment]
I am using `Django3` from `master` branch with commit `c610dd9c7871f4e81bdffce783df8b040ca22878`
Here is the `requirements.txt` Assume you willing to run `master`
`-e git+git@github.com:jazzband/django-push-notifications.git@master#egg=django-push-notifications`

**Comment by iamareebjamal** [comment]
You shouldn't use master branch, use a specific commit

**Comment by iamareebjamal** [comment]
@jleclanche Can we please get the latest version released on PyPI?

**Comment by jleclanche** [comment]
This is part of jazzband, I don't think I'm the only one able to make a release. I'm currently busy with other matters but don't let anything be blocked on me.

**Comment by jamaalscarlett** [comment]
I can look into it today.  What is the commit hash for the version?

**Comment by iamareebjamal** [comment]
@jamaalscarlett Latest on master which is more than a month old https://github.com/jazzband/django-push-notifications/commit/c610dd9c7871f4e81bdffce783df8b040ca22878

**Comment by jamaalscarlett** [comment]
@jleclanche can you add the pypi api token as a secret. I am not able to see the Settings tab.  Once that is done, I can set up the github workflow and deploy the new version.

**Comment by jleclanche** [comment]
I don't have access to the settings tab either.

**Comment by jleclanche** [comment]
@jamaalscarlett I can add you as another owner on pypi though, what's your username there?

**Comment by jamaalscarlett** [comment]
@jleclanche my username is: jamaalscarlett

**Comment by jleclanche** [comment]
@jamaalscarlett you need a verified primary email address to be added as owner.

**Comment by jamaalscarlett** [comment]
@jleclanche  OK, email address has been verified.

**Comment by jleclanche** [comment]
Done. Let me know if you need anything else.

**Comment by jheld** [comment]
Do we have any updates here? Our project is also needing this in. We'd be more than happy to help test it, too.

**Comment by jamaalscarlett** [comment]
https://github.com/jazzband/django-push-notifications/releases/tag/2.0.0
https://pypi.org/manage/project/django-push-notifications/release/2.0.0/

I still need to fix the release notes, but it is available to download.
