### ISSUE TITLE
Sending APNS notification to devices without application ID

### ISSUE THREAD

**Issue by captain-fox** [jazzband/django-push-notifications#553]
I'm looking for a library to send APNS notifications to passes in Wallet app on iOS devices. This means I don't need/have application ID, but only use push token and Pass Type ID instead. After I've looked into implementation of this package there's mandatory `application_id` parameter all over the place. Is there any way to use this library bypassing (without) `application_id`?

**Comment by elcolie** [comment]
I confirm. I am using my configuration without `application_id`. It is legacy and fading out now you can check from `master` Here are my config

`base.py`
```python
PUSH_NOTIFICATIONS_SETTINGS = {
        "FCM_API_KEY": "AAAAQRdHxu...............xxxxxxxxx",
        "APNS_CERTIFICATE": str(APPS_DIR) + '/push_noti/my_cert.pem',
        "APNS_USE_SANDBOX": "api.sandbox.push.apple.com:443",
        "WP_PRIVATE_KEY": str(APPS_DIR) + "/push_noti/private_key.pem",
        "WP_CLAIMS": {'sub': "mailto: sarit@elcolie.com"},
        "UPDATE_ON_DUPLICATE_REG_ID": True,
}
```

`production.py`
```python
PUSH_NOTIFICATIONS_SETTINGS['APNS_CERTIFICATE'] = str(APPS_DIR) + '/push_noti/ff/production_com.xxx.yyy.zzz.pem'
PUSH_NOTIFICATIONS_SETTINGS['APNS_USE_SANDBOX'] = False
PUSH_NOTIFICATIONS_SETTINGS['APNS_TOPIC'] = "com.xxx.yyy.zzz"
```
