### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by orimboolak** [jazzband/django-push-notifications#554]
I keep getting this error even after i pull the latest changes. Kindly help

**Comment by elcolie** [comment]
Try `pyenv` and work with `Python3`

**Comment by chellyxia** [comment]
Changes in https://github.com/jazzband/django-push-notifications/pull/544/files are not reflect when installing using `pip install django-push-notifications`

`python_2_unicode_compatible` and `six.string_types` errors persist.

**Comment by iamareebjamal** [comment]
@chellyxia Because the last release is of Aug 2019, new version hasn't released yet

**Comment by rjdebastiani** [comment]
I'm having this same issue here, any suggestions for a workaround while the new version is not released?

**Comment by iamareebjamal** [comment]
https://github.com/jazzband/django-push-notifications/issues/550#issuecomment-585546864

**Comment by jamaalscarlett** [comment]
python 3 is now required
