### ISSUE TITLE
BadDeviceToken after download app from `App Store`

### ISSUE THREAD

**Issue by elcolie** [jazzband/django-push-notifications#556]
I build app from source code. APNS works and no delay
After I publish my app to App Store `regirstration_id` gives me this error
```bash
In [17]: APNSDevice.objects.filter(user__username__icontains='duck', registration_id='c2e9d4ec4c769314fef2175d47324be3292732d44
    ...: 8a12e1c58021906958a92a1').send_message("Test7")
Out[17]: [{'c2e9d4ec4c769314fef2175d47324be3292732d448a12e1c58021906958a92a1': 'BadDeviceToken'}]

In [18]: APNSDevice.objects.filter(user__username__icontains='duck', registration_id='798a23a46169e405c41a0c9f44faa0acd39a65119
    ...: 960b973acd248a6de1d624e').send_message("Test8")
Out[18]: [{'798a23a46169e405c41a0c9f44faa0acd39a65119960b973acd248a6de1d624e': 'Success'}]
```

Is there any one here can shed me the light please?

**Comment by nlittlejohns** [comment]
Hard to tell, but I would guess one of the following:

- The device was registered on your sandbox environment and is using a stored device token. Try deleting the app from the device, ensuring all user data and keychain entries are erased, then re-install from the App Store. Then remove the device registration from your Django Admin.
- Perhaps you're using a sandbox certificate in production? Less likely from the error given, but check you're definitely using your production certificate.

**Comment by elcolie** [comment]
@nlittlejohns Yes you are right
`PUSH_NOTIFICATIONS_SETTINGS['APNS_USE_SANDBOX'] = False`
I was confused with doc and code base

**Comment by nlittlejohns** [comment]
@elcolie I recommend you use python-decouple for things like this (if you're not already!)
https://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html

`    "APNS_USE_SANDBOX" : config('APNS_USE_SANDBOX', default=False, cast=bool),`
