### ISSUE TITLE
Tip: requestPOSTToServer implementation for Web Push

### ISSUE THREAD

**Issue by nlittlejohns** [jazzband/django-push-notifications#557]
Got a bit stuck implementing Web Push when the sample code makes a call to "requestPOSTToServer", which doesn't exist.

Thanks to this [blog post](https://www.monotalk.xyz/blog/django-push-notifications-を使ってweb-push-通知を実装する/), I was able to figure out a solution using Ajax and a small Django view.

(uses jQuery's Ajax support)

Add this function to your Javascript:

```
function requestPOSTToServer ( data ) {
    $.ajax({
        url: '/ajax/device/wp/',
        data: {
            'browser': data.browser,
            'p256dh': data.p256dh,
            'auth': data.auth,
            'registration_id': data.registration_id
        },
        dataType: 'json',
        success: function (data) {
        }
      });
}
```

Add this view to your Django app:

```
from django.http import JsonResponse
from push_notifications.models import WebPushDevice

def register_wp_notifications(request):
    WebPushDevice.objects.create(
        registration_id=request.GET.get('registration_id'),
        p256dh=request.GET.get('p256dh'),
        auth=request.GET.get('auth'),
        browser=request.GET.get('browser'),
        user=request.user,
    )
    data = {
        'result': True
    }
    return JsonResponse(data)
```

**Add a path in your urls.py to make it accessible!**

When you're done you should be able to register Web Push devices.

BONUS TIP: I think there's an error in the sample code. The line which reads
`        var browser = loadVersionBrowser();`
Should probably read:
`        var browser = loadVersionBrowser( navigator.userAgent );`

Hope this saves someone some time.

**Comment by nlittlejohns** [comment]
**Bonus Bonus Tip**
Web Push in django-push-notifications doesn't support kwargs like "extra" in the same way as APNS and GCM, but instead you can send a message with any JSON you like. You just need to serialize it first:

```
import json

data = json.dumps({"title": title, "message": message})
wp_devices.send_message(data)
```

This will set the "Title" and "Message" fields. It looks as though to support other items like "icon" etc, you'll need to edit navigatorPush.service.js (or replace it with a different implementation).

**Comment by nlittlejohns** [comment]
> Hey, thanks for the tips. How did you get your APNS working? I am struggling to retrieve a device token. And also getting BadDeviceToken the whole time. I would really appreciate it if you can maybe point me in the right direction.

I did get it working, but it was so long ago that I don't remember what I had to do, and I don't know if the code I wrote is still working because it's not currently in use. Sorry I can't be of more help!

**Comment by Theunis111** [comment]
Really appreciate the reply. Thanks a lot
