### ISSUE TITLE
Have ImproperlyConfigured exception with looks perfect config

### ISSUE THREAD

**Issue by VladConan** [jazzband/django-push-notifications#573]
Trying to send a test message from Django admin. (APNS)
Getting this exception:
"You need to setup PUSH_NOTIFICATIONS_SETTINGS properly to send messages"
my config is 
PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_TOPIC": "com.some.app",
    "APNS_AUTH_KEY_PATH": os.path.join(BASE_DIR, "AuthKey.p8"),
    'APNS_KEY_ID': 'MY_KEY_ID',
    'APNS_TEAM_ID': 'MY_TEAM_ID',
    "APNS_USE_SANDBOX": True,
   "UNIQUE_REG_ID": True,
    "UPDATE_ON_DUPLICATE_REG_ID": True,
}
TOPIC, KEY_ID,  TEAM_ID redacted
What's wrong?

**Comment by adrianp** [comment]
@VladConan should be `APNS_AUTH_KEY_ID` instead of `APNS_KEY_ID`.
