### ISSUE TITLE
dependency on outdated hyper/h2 package

### ISSUE THREAD

**Issue by dashdanw** [jazzband/django-push-notifications#583]
I use grpc in tandem with apns notifications, currently the latest release of django-push notifications seems fundamentally incompatible with some of the new features/changes in hyper 3.0+ I'm not sure the best way to solve this but I'd be happy to take a crack if someone can point me in the right direction.

**Comment by krishnasadhu9** [comment]
@dashdanw Even I face the same issue, is there any way to solve it.

**Comment by mcepl** [comment]
Just mentioning https://github.com/Pr0Ger/PyAPNs2/issues/74

**Comment by auvipy** [comment]
trying to upgrade the dependencies would be the right direction.

**Comment by daveisfera** [comment]
I think you're looking for the changes in `apns2` to be released (see [here](https://github.com/Pr0Ger/PyAPNs2/issues/74) and [here](https://github.com/Pr0Ger/PyAPNs2/issues/126))

**Comment by azmeuk** [comment]
Closing in favor of #622
