### ISSUE TITLE
Not receiving notification on Google Chrome Browser. 

### ISSUE THREAD

**Issue by salad-henchmen** [jazzband/django-push-notifications#592]
I've implemented the web push for a project and it works fine on the Firefox browser. However, when I tested it out with Google Chrome, it didn't appear. There is no error either. The message is lost. Have I missed something? The server and the front end run separately. Could the different domains be the issue?

**Comment by salad-henchmen** [comment]
https://stackoverflow.com/questions/53161161/django-push-notification-401-unauthorised

**Comment by datt3010** [comment]
@salad-henchmen , are you run web push on https ? because it not support for http
