### ISSUE TITLE
FCM error while pushing to Android

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [jazzband/django-push-notifications#594]
Hi,

After struggle of hours and re-checking every part of code I just am having this error as provided below:

GCMError: {'multicast_id': 1595940385679552100, 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'MismatchSenderId', 'original_registration_id': '["My API Key in quotes was here."]'}]}
.

Would really appreciate if someone can advise .

Best Regards,
Cheers.

**Comment by jamaalscarlett** [comment]
This is a server side error indicating that your registration id has changed.  @MUDASSARHASHMI  is this still an issue?

**Comment by jamaalscarlett** [comment]
Closing since there has been no response from the original poster.

**Comment by datt3010** [comment]
hi @jamaalscarlett , i have same problem, can you help me sir ?
