### ISSUE TITLE
Missing documentation for WebPush using the new config

### ISSUE THREAD

**Issue by jpaav** [jazzband/django-push-notifications#610]
The [Wiki page](https://github.com/jazzband/django-push-notifications/wiki/Multiple-Application-Support) for the new Config does not include details for WebPush and makes it seem like it is not an option. From the page:

> The value is a dictionary that must contain the key PLATFORM. PLATFORM must be one of APNS, FCM, GCM, or WNS.

**Comment by azmeuk** [comment]
#674 comes with better documentation for webpush
