### ISSUE TITLE
can i use firebase for iOS instead of APNS?

### ISSUE THREAD

**Issue by Bashar** [jazzband/django-push-notifications#611]
I tried to comment out APNS parts from PUSH_NOTIFICATIONS_SETTINGS but it gave the error 

You need to setup PUSH_NOTIFICATIONS_SETTINGS properly to send messages

is it possible to use firebase for IOS instead of APNS?

**Comment by AxelHgt** [comment]
Hi,
Yes you need to setup settings to make it work.
And the APNS part is not required.

Example:
```
PUSH_NOTIFICATIONS_SETTINGS = {
    'USER_MODEL': 'users.User',
    'FCM_API_KEY': os.environ.get('FCM_KEY'),
    'UPDATE_ON_DUPLICATE_REG_ID': True
}
```

**Comment by ayushin** [comment]
We do this:

https://github.com/jazzband/django-push-notifications/pull/615
