### ISSUE TITLE
changing `active` state on the `push_notifications_gcmdevice` table

### ISSUE THREAD

**Issue by Avramo** [jazzband/django-push-notifications#616]
Hi!

I use django with django-push-notifications. 
When sending push notifications, I would like to know which users did/didn't get the message.

Currently I use this code after sending the notifications to know how many were sent/not sent:
```
    all_users = queryset.count()
    active_fcm = GCMDevice.objects.filter(user_id__in=queryset.values_list('id', flat=True), active=True).count()
    return Response({
        'sent': active_fcm, 
        'not_sent': all_users - active_fcm
        }, status=status.HTTP_201_CREATED)
```
I noticed this is not 100% accurate as the `active` field does not always reflect the actual users' status.
I removed the app and the `active` field was still `True`.

When and how does the `active` column in the `push_notifications_gcmdevice` table change?

Also what  does `device.send_message()` return, and what is the meaning of success (ie. sent, active, or received)?

**Comment by henderson2350** [comment]
Is there a way to tell if a user has ENABLED push notifications on their device? not just whether or not the device has been registered?

**Comment by jamaalscarlett** [comment]
That would have to be handled via your android/ios/webapp.  i.e. on the device, if the user disables notifications, you should send a request to your server to update the device model

**Comment by jamaalscarlett** [comment]
@henderson2350 I just tried this with FCM.  Even when I disable app notifications on the phone, the notification is sent successfully from the backend.  The blocking is occurring on the phone, so the detection would need to occur there.
