### ISSUE TITLE
How to register for webpush?

### ISSUE THREAD

**Issue by yandiro** [jazzband/django-push-notifications#647]
Hello! Congrats and thanks for doing this app, by the way!

I have to say, thought, that it is a bit confusing on how to register a browser to get a notification. 

I followed Firebase's guide on how to get a registration id for the browser and it worked fine, I could even send a notification to my test web app via Firebase's notification test.

I tried to create a device on django_push_notifications with this same registration ID, and I could not, because it asks for 2 more fields (User public encryption key and User auth secret), of which the documentation makes no mentions (or it is very hard to find). If I try to use this same registration id created for a browser on the FCM / GCM, I get an error (INVALID_KEY_TYPE).

Is there any documentation on how to get this working on a browser? 

Also, an overall clearer documentation would be much appreciated (I did read some of the issues people posted) by the community.

Regards!!

**Comment by shawnngtq** [comment]
I don't find tutorial for this library. Would love to use it though.

Anyone can share URLs? For beginners who never work with APNS, FCM/GCM, WNS and WebPush.

**Comment by blighj** [comment]
@shawnngtq  @yandiro Any feedback on this PR, #674, specfically this file, which aims to explain wepush configuration
https://github.com/jazzband/django-push-notifications/blob/4fb64be08a5e9d4b9275e9632426d022d5a84a70/docs/WebPush.rst

**Comment by azmeuk** [comment]
Fixed by #674
