### ISSUE TITLE
Cannot send push notification to Firefox (on Android)

### ISSUE THREAD

**Issue by nicolazilio** [jazzband/django-push-notifications#657]
Hi all,

I am experiencing a browser- and platform-specific failure of delivering notifications. I can successfully push notifications to all supported browsers on both desktop and Android except Firefox on Android. When I try that, I get 

Push failed: 404 Not Found
Response body: 
{"code": 404, 
"errno": 102, 
"error": "Not Found", 
"more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", 
"message": "Request did not validate invalid token"}

According to https://autopush.readthedocs.io/en/latest/http.html#error-codes errno 102 means 'Invalid URL endpoint'. Why would this happen on Android but not on Desktop? Is this a problem with django-push-notifications or rather pywebpush?

Thank you in advance

**Comment by blighj** [comment]
The mergeing of #674 should also fix this issue, for new devices registered.

**Comment by azmeuk** [comment]
Fixed by #674
