### ISSUE TITLE
requestPOSTToServer is not defined

### ISSUE THREAD

**Issue by Alzabel999999** [jazzband/django-push-notifications#658]
In your js cannot find function requestPOSTToServer. Where I can get it?

**Comment by viktorisacenko** [comment]
#665

**Comment by blighj** [comment]
@Alzabel999999
Any feedback on this PR, #674, specfically this file, which aims to explain wepush configuration
https://github.com/jazzband/django-push-notifications/blob/4fb64be08a5e9d4b9275e9632426d022d5a84a70/docs/WebPush.rst

**Comment by azmeuk** [comment]
Until #674 is merged, you can find an implementation in the README:

https://github.com/jazzband/django-push-notifications/blob/bd387e954318469af227a2a6cb89c225c4ca5092/README.rst?plain=1#L383-L396
