### ISSUE TITLE
how to tell which devices have notifications actually enabled

### ISSUE THREAD

**Issue by henderson2350** [jazzband/django-push-notifications#666]
sort of similar to #616 , I'm wondering if there's a good way to tell on the backend whether or not a device actually has notifications enabled, without having to pass this information from the front end.

The context is that I want to send push notifications to user's devices only if they actually have them enabled, but I'm sending them from a separate application (website), so I'd need to access the information remotely from there

**Comment by jamaalscarlett** [comment]
@henderson2350 I think this needs to be handled in your app not dpn.  So if the user turns off notifications, your backend app should update the active field on the device model

**Comment by simonkern** [comment]
@jamaalscarlett is absolutely right. However, there are cases in which you'll only notice a device is gone, only after getting an exception (e.g. "410 Gone") while trying to send a webpush to that device. You could check for such an exception within a try block and deactivate the underlying device upon encountering it:

``` python
from push_notifications.exceptions import WebPushError

def send_webpush(user, title, msg, url=None):
    # get user and its registered webpush devices
    wp_devices = user.webpushdevice_set.filter(active=True)
    # if user has no registered push devices -> return
    if not wp_devices.exists():
        return

    # Otherwise prepare payload and push to all devices
    payload = {
        "title": title,
        "message": msg,
    }
    # add url if given
    if url:
        payload.update({"url": url})
    # prepare json payload
    json_payload = json.dumps(payload)
    # push to all devices
    for wpd in wp_devices:
        try:
            wpd.send_message(json_payload)
        except WebPushError as e:
            if "410 Gone" not in str(e):
                # deactivate no longer available wpd
                wpd.active = False
                wpd.save()
                continue
            raise e

```
