### ISSUE TITLE
No exception message supplied

### ISSUE THREAD

**Issue by datt3010** [jazzband/django-push-notifications#681]
I'm testing send message for FCM but error NotImplementedError.
My config:
```python
      "PLATFORMS": {
            "PLATFORM": "FCM",
            "API_KEY": "AAAAhV8XZbc:APA91bHN93fL-dm91zoBOKygcwPMhcmwgRjd9Tc9UMB5AmepG9W0wCfvVJJ5qGGsm8T0GNNev"
                           + "HqQacxnIx3lZANNgVDAIYoMFNrAioHcM-oMBDqwHFOmexDHXx2im29p-mkBCRQA5eUX",
            "POST_URL": "https://fcm.googleapis.com/fcm/send",
            "MAX_RECIPIENTS": 1000,
            "ERROR_TIMEOUT": None,
        }
``` 
![image](https://github.com/jazzband/django-push-notifications/assets/86698500/5ba3fcd6-d285-4fb0-b991-4313e7b2c8b1)

Althougt running on https but it still error.
Sorry for my bad english.

**Comment by jamaalscarlett** [comment]
@datt3010 The Error is coming from your koolyard code, not dpn.

**Comment by datt3010** [comment]
@jamaalscarlett  Thanks sir, I solved since 2 weeks ago
