### ISSUE TITLE
Some messages could not be processed: "{'multicast_id': 6582246459593262801, 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results'

### ISSUE THREAD

**Issue by datt3010** [jazzband/django-push-notifications#682]
I'm test notification FCM on browser My problem is:
Some messages could not be processed: "{'multicast_id': 6582246459593262801, 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'MismatchSenderId', 'original_registration_id': 'API_KEY'}]}"
how can i solve it ?
thanks you.

**Comment by datt3010** [comment]
@jamaalscarlett Thanks sir, I solved it since 2 weeks ago 👍

**Comment by MinRahim** [comment]
I have the same issue. I run on the browser, and the notification should be sent to Android but got error {'multicast_id': 700428736517436844, 'success': 0, 'failure': 1, 'canonical_ids': 0, 'results': [{'error': 'DeprecatedApi', 'original_registration_id': 'APP_ID'}]}. I use django-push-notifications v3.0.0. This has still worked before, but now I have not received any notification. What did I need to do?

Thank you.
