### ISSUE TITLE
A valid push subscription endpoint should be specified in the URL

### ISSUE THREAD

**Issue by Wizely99** [jazzband/django-push-notifications#686]
Hello i've setup my django app but at the end i cant send notification to subscribed devices.I get the error as below
`Push failed: 404 Not Found
Response body:A valid push subscription endpoint should be specified in the URL as such: https://fcm.googleapis.com/wp/dHIoDxE7Hdg:APA91bH1Zj0kNa...`
My settings are as follows

```python
PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": "AAAAG3r9SiQ:APA91bFuZSc8e2byueLAmz06MUdwQhQiUHMUjY5aKS8XZ4GVqjsxMPGxMKLEN_-dEczIbhxBiff3rGdOP90Q35JADHZBAKTDG_pfthVjCHA-iJmYjv4JJtQSmR_fyv4hPJJwoRs3bKQE",

    "APP_SERVER_KEY": "BJirBzxWJiOu9ZSpp0AQN7ER92RYczrBbTlFdyRSdpFB3W6aOXUYArl4Xp7w0WAz7XWSHspqQoz___M6cW0nxzc",

    "WP_PRIVATE_KEY": os.path.join(BASE_DIR, "private_key.pem"),

    "WP_CLAIMS": {"sub": "mailto: hermanpaul050597@gmail.com"},

    "WP_ERROR_TIMEOUT": 10,  # timeout for the request on the push server

    "UPDATE_ON_DUPLICATE_REG_ID": True,
}
```

**Comment by jamaalscarlett** [comment]
@Wizely99  What is WP_POST_URL set to?

**Comment by Wizely99** [comment]
@jamaalscarlett I used https://fcm.googleapis.com/fcm/send the default one

**Comment by azmeuk** [comment]
With #674, the endpoint used to send notifications is the one provided by the push server. Wouldn't this fix this issue?

**Comment by jamaalscarlett** [comment]
@Wizely99 what is the full endpoint you are attempting to send to.  As the error states it should be:
https://fcm.googleapis.com/wp/<SOME_CHARS>:<MORE_CHARS>. The endpoint should be stored as the registration_id on the device.

**Comment by Wizely99** [comment]
I think I still don't understand som few things as this is my first project using web push in django.Although I have prior experience with push notifications through OneSignal, I am relatively new to utilizing the `django-push-notifications` package.After reading the documentation i didnt understand how to set the FCM_POST_URL as the documentations says  `FCM_POST_URL: The full url that FCM notifications will be POSTed to. Defaults to https://fcm.googleapis.com/fcm/send.`.I tried to look for such url in `firebase console` but i was not able to achieve that.I would appreciate any help on setting the valid url to push notifications using firebase or any other service or a minimum working repo could be of great assistance to me.

**Comment by Wizely99** [comment]
Thanks it worked.I was using `GCMDevice` instead of `WebPushDevice` to send the notifications
