### ISSUE TITLE
WebPush is successfully sent but never received by iOS device using example WP_CLAIMS configuration

### ISSUE THREAD

**Issue by o-s-m-o-s** [jazzband/django-push-notifications#701]
When using the default configuration for Webpush given in the docs Pushes are reported as successfully send but not received by iOS devices.

Changing:
`"WP_CLAIMS": {'sub': "mailto:development@example.com"}`
to
`WP_CLAIMS":  {"sub": "mailto:YourEmailAddress"}` as used in the [pywebpush docs](https://github.com/web-push-libs/pywebpush) meant the push was received successfully.

My guess is that Apple is silently rejecting the Push but can't confirm this.

Happy to make a very small edit to the push-notifications docs if this is a reproducible problem for others.

**Comment by 50-Course** [comment]
Hi,

May I know what response you are getting? 

This should work for you,
```python

PUSH_NOTIFICATIONS_SETTINGS = {
	"WP_CLAIMS": {"sub": "mailto:jazzband@example.com"}
}
```

which follows the `pywebpush` description of `vapid_claims`:

```python
from pywebpush import webpush, WebPushException

try:
    webpush(
        ...
        data="Mary had a little lamb, with a nice mint jelly",
        vapid_claims={
                "sub": "mailto:YourNameHere@example.org",
            }
    )
except WebPushException as ex:
    print("I'm sorry, Dave, but I can't do that: {}", repr(ex))
    ...
```

**Comment by o-s-m-o-s** [comment]
When I opened this issue the pywebpush response was reporting a successful push but on iPhone the notification was never received. After changing the email in the sub field of the WP_CLAIMS the pushes were still reporting success but also being received.

Today I wanted to double-check and tried to reproduce this issue and the web push went through without issue with the WP_CLAIMS as in the current django-push-notifications documentation.

I'll close this issue as I can't reproduce it.
