### ISSUE TITLE
Timeline for the next release

### ISSUE THREAD

**Issue by intonarumori** [jazzband/django-push-notifications#705]
Hello everyone.

Is there a timeline for the next release that would include the updated FCM APIs?
We have a project using this library and have to make a decision on either using the development version, migrate away or wait for an official release that we can use in our production code.

Unfortunately we only have couple of weeks to decide, so it would be great to hear from the team about the plans.
If you need help with the release we might be able to dedicate some dev time on this, review or update PRs to get them over the line etc.

Let us know how we can help to move things forward, thanks.

**Comment by silviogutierrez** [comment]
@intonarumori : have you found alternatives? I spent a few hours trying to get this to work with Python 3.12 but am about to give up.

**Comment by 50-Course** [comment]
Hello @intonarumori, unfortunately the package does not have specified release schedules at the moment, however, given its recent major upgrades. It is safe to push out a new tagged release for an update. @jamaalscarlett can you look into this?

Thank you!

**Comment by aleksaterzic** [comment]
Hello everyone, are there any updates regarding the new release? In the same position as @intonarumori 
If there's anything we can do to speed up the process and move things forward please let us know.

**Comment by jamaalscarlett** [comment]
I'd like to get https://github.com/jazzband/django-push-notifications/pull/699 into the release.  Should be this week.  I will cut a release as soon as that PR is merged.

**Comment by guspix** [comment]
I just submitted #712, which I think should make it into this release, since FCM functionality will still break in June unless we address it. I'm not sure if I'm missing something, but I can see that the code in master uses `messaging.send_all`, which will stop working in June, instead of `messaging.send_each`, and I don't see open pull requests to address it. It should be a one line change, plus changing the tests. Let me know and I can try to submit a PR with the fix, though I haven't tried it yet.

**Comment by PureTryOut** [comment]
https://github.com/jazzband/django-push-notifications/pull/715 will fix the last issue.

Reminder that the currently released version of django-push-notifications will **stop working in June**. Please don't release a new version only the last minute, projects need time to upgrade and it's preferable to have a little bit of time for that.

**Comment by jamaalscarlett** [comment]
I created an issue to drop python 3.6.  I will get that change in tonight, or someone else can do it.  Then I will cut a new release.

**Comment by jamaalscarlett** [comment]
https://pypi.org/project/django-push-notifications/3.1.0/
