### ISSUE TITLE
Python 3.12:  Cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by coratype** [jazzband/django-push-notifications#731]
apparently this was fixed here by using aioapns instead of apns2 but that does not seem to be the case 

https://github.com/jazzband/django-push-notifications/pull/696

`cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/collections/__init__.py)`

**Comment by jamaalscarlett** [comment]
This is a duplicate
